[package]
name = "allowed-dns"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/octylFractal/allowed-dns"

[dependencies]
dns-lookup = "1.0.5"
